<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    public function save(array $options = [])
    {

        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
